"""Cross-session agent memory: module context + refactor history."""

from __future__ import annotations

import json
from pathlib import Path

from refactorika.core.schema import EditRecord, ModuleContext
from refactorika.core.storage import Storage

_CTX_KEY = "refactorika:memory:context"


class AgentMemory:
    def __init__(self, storage: Storage) -> None:
        self._storage = storage

    # --- module context -------------------------------------------------------

    def put_context(self, module: str, ctx: ModuleContext) -> None:
        """Persist a ModuleContext for a module (survives sessions)."""
        payload = json.dumps(ctx.to_dict())
        if self._storage._redis:
            self._storage._redis.hset(_CTX_KEY, module, payload)
        else:
            data = self._storage._read_state()
            data.setdefault("context", {})[module] = ctx.to_dict()
            self._storage._write_state(data)
        self._write_md(module, ctx)

    def get_context(self, module: str) -> ModuleContext | None:
        """Retrieve a prior ModuleContext, or None on cold cache."""
        if self._storage._redis:
            raw = self._storage._redis.hget(_CTX_KEY, module)
            if raw:
                return ModuleContext.from_dict(json.loads(raw))
        else:
            data = self._storage._read_state()
            entry = data.get("context", {}).get(module)
            if entry:
                return ModuleContext.from_dict(entry)
        return None

    def all_contexts(self) -> dict[str, ModuleContext]:
        if self._storage._redis:
            raw = self._storage._redis.hgetall(_CTX_KEY)
            return {k: ModuleContext.from_dict(json.loads(v)) for k, v in raw.items()}
        data = self._storage._read_state()
        return {
            k: ModuleContext.from_dict(v)
            for k, v in data.get("context", {}).items()
        }

    # --- refactor history ----------------------------------------------------

    def history(self, file: str | None = None) -> list[dict]:
        """Return edit records (optionally filtered by file path)."""
        log = self._storage.get_log()
        if file is None:
            return log
        return [r for r in log if file in r.get("files", [r.get("file", "")])]

    # --- .md file sidebar ----------------------------------------------------

    def _write_md(self, module: str, ctx: ModuleContext) -> None:
        ctx_dir = Path(".refactorika/context")
        ctx_dir.mkdir(parents=True, exist_ok=True)
        slug = module.replace("/", ".").removesuffix(".py")
        md_path = ctx_dir / f"{slug}.md"
        exports_block = "\n".join(
            f"- `{e.name}` ({e.kind}): `{e.signature}`" for e in ctx.exports
        ) or "_(none detected)_"
        dependents_block = "\n".join(f"- {d}" for d in ctx.dependents) or "_(none detected)_"
        flagged_block = "\n".join(f"- {f}" for f in ctx.flagged) or "_(none detected)_"
        decisions_block = "\n".join(f"- {d}" for d in ctx.decisions) or "_(none yet)_"
        # The inferred purpose hint is a *seed* for Claude's prose, not a fact.
        purpose_seed = (
            f"_Inferred hint:_ {ctx.purpose_hint}"
            if ctx.purpose_hint and ctx.purpose_hint != "<!-- claude: fill -->"
            else ""
        )
        run_block = ctx.last_updated_run or "_(unknown)_"
        text = f"""# {slug}

> This file has two halves: **Extracted (facts)** is written deterministically by
> Refactorika from the code. **Needs Claude** is prose for Claude to fill in.

## Extracted (facts)
_Generated by Refactorika from the source — do not hand-edit; it is regenerated._

### Exports
{exports_block}

### Dependents
{dependents_block}

### Flagged patterns
{flagged_block}

### Last updated run
{run_block}

---

## Needs Claude
_Prose below is for Claude to write/refine in-conversation._

### Purpose
{purpose_seed}
<!-- claude: fill — what this module is for, in 1-2 sentences -->

### Decisions / Why
{decisions_block}
<!-- claude: fill — non-obvious design decisions and their rationale -->
"""
        md_path.write_text(text)
